openapi: 3.0.0
info:
  version: 1.0.0
  title: Sentiment AI
  description: A sample API to illustrate OpenAPI concepts

paths:
  /{api_provider}/places/{place_id}:
    get:
      description: Returns a list of 50 reviews for a place              
      responses:
        '200':
          description: Successful response
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/PlaceReview"
      
  /{api_provider}/places/{place_id}/{review_count}:
    get:
      description: Returns a list of reviews for a place              
      responses:
        '200':
          description: Successful response
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/PlaceReview"


  /entity/{entity_name}/{review_count}:
    get:
      description: Returns a list of reviews for an entity              
      responses:
        '200':
          description: Successful response
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Review/EntitiesScore"

  /entities/{review_count}:
    get:
      description: Returns a list of reviews for all entities              
      responses:
        '200':
          description: Successful response
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Review/EntitiesScore"

components:
  schemas:
    PlaceReview:
      type: object
      properties:
        id:
          type: integer
          format: int64
        place:
          ref: '#/components/schemas/Place'
        review:
          ref: '#/components/schemas/Review'
        rating:
          type: integer
          format: int32
        api_provider:
          type: string
    Place:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        address:
          type: string
    Review:
      type: object
      properties:
        id:
          type: integer
          format: int64
        text:
          type: string
        sentiment_score:
          type: number
        entities_score:
          type: array
          items:
            ref: '#/components/schemas/EntitiesScore'
        language:
          type: string
        date:
          type: string
          format: date-time
      EntitiesScore:
        type: object
        properties:
          name:
            type: string
          sentiment_score:
            type: number
          confidence_score:
            type: number
    